apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kanister-operator.fullname" . }}-profile-creds
type: Opaque
data:
  aws_access_key_id: {{ required "Cloud provider API key is required when configuring a profile." .Values.profile.creds.s3_api_key | b64enc | quote }}
  aws_secret_access_key: {{ required "Cloud provider API secret is required when configuring a profile." .Values.profile.creds.s3_api_secret | b64enc | quote }}
---
apiVersion: cr.kanister.io/v1alpha1
kind: Profile
metadata:
  name: {{ template "kanister-operator.fullname" . }}-profile
location:
  type: s3Compliant
  s3Compliant:
    bucket: {{ required "S3 compatible bucket is required when configuring a profile." .Values.profile.location.s3_bucket |  quote }}
    endpoint: {{ .Values.profile.location.s3_endpoint | quote }}
    prefix: {{ .Values.profile.location.s3_prefix | quote }}
    region: {{ .Values.profile.location.s3_region | quote }}
credential:
  type: keyPair
  keyPair:
    idField: aws_access_key_id
    secretField: aws_secret_access_key
    secret:
      apiVersion: v1
      kind: Secret
      name: {{ template "kanister-operator.fullname" . }}-profile-creds
skipSSLVerify: {{ .Values.profile.s3_verify_ssl }}
